data:
data_path: data/winequality-red.csv
target_column: quality

model:
  type: RandomForestRegressor
  n_estimators: 100
  max_depth: 8
  random_state: 42

split:
  test_size: 0.2
  random_state: 42
